apiVersion: v1
kind: ConfigMap
metadata:
  name: rocket-ecommerce-config
  namespace: prod
data:
  DEBUG: "FALSE"
  FLASK_APP: "run.py"
  FLASK_DEBUG: "False"
  STRIPE_SECRET_KEY: "sk_test_51Qvz3wB4uenaBfEAhfhUfG0CJ8Tll479cYVttRcfz0GBX5kBijp3UCpBoO2tDDU6suqqMC1kOKvYnoRW6vycmpfI00cORvbpl3"
  STRIPE_PUBLISHABLE_KEY: "pk_test_51Qvz3wB4uenaBfEAnW9cl2LSjNYsZbM2iT49TCdmNwGAWQPvp2oZyoo7b6zu4wNtnXP6gCP1DAVGrNctZogycGze00v9hERuJA"
  SERVEUR_ADDRESS: "http://localhost:5005/"