apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocket-ecommerce-deployment
  namespace: prod
  labels:
    app: rocket-ecommerce
spec:
  replicas: 1  # Ajustable selon la charge
  selector:
    matchLabels:
      app: rocket-ecommerce
  template:
    metadata:
      labels:
        app: rocket-ecommerce
    spec:
      containers:
      - name: rocket-ecommerce
        image: floriangeoffr/rocket-ecommerce:latest
        ports:
        - containerPort: 5005
        envFrom:
        - configMapRef:
            name: rocket-ecommerce-config
