apiVersion: v1
kind: Service
metadata:
  name: rocket-ecommerce-service
  namespace: prod
spec:
  selector:
    app: rocket-ecommerce
  type: NodePort  # Changeable en LoadBalancer ou ClusterIP
  ports:
    - port: 80
      targetPort: 5005
      nodePort: 30080  # Accessible sur ce port
