apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocket-ecommerce-deployment
  namespace: dev
  labels:
    app: rocket-ecommerce
spec:
  replicas: 1  # Ajustable selon la charge
  selector:
    matchLabels:
      app: rocket-ecommerce
  template:
    metadata:
      labels:
        app: rocket-ecommerce
    spec:
      containers:
      - name: rocket-ecommerce
        image: floriangeoffr/rocket-ecommerce:latest
        ports:
        - containerPort: 5005
        envFrom:
        - configMapRef:
            name: rocket-ecommerce-config

---

apiVersion: v1
kind: Service
metadata:
  name: rocket-ecommerce-service
  namespace: dev
spec:
  selector:
    app: rocket-ecommerce
  type: NodePort  # Changeable en LoadBalancer ou ClusterIP
  ports:
    - port: 80
      targetPort: 5005
      nodePort: 30080  # Accessible sur ce port

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rocket-ecommerce-config
  namespace: dev
data:
  DEBUG: "FALSE"
  FLASK_APP: "run.py"
  FLASK_DEBUG: "False"
  STRIPE_SECRET_KEY: "sk_test_51Qvz3wB4uenaBfEAhfhUfG0CJ8Tll479cYVttRcfz0GBX5kBijp3UCpBoO2tDDU6suqqMC1kOKvYnoRW6vycmpfI00cORvbpl3"
  STRIPE_PUBLISHABLE_KEY: "pk_test_51Qvz3wB4uenaBfEAnW9cl2LSjNYsZbM2iT49TCdmNwGAWQPvp2oZyoo7b6zu4wNtnXP6gCP1DAVGrNctZogycGze00v9hERuJA"
  SERVEUR_ADDRESS: "http://localhost:5005/"