# Generated by Django 4.2.9 on 2024-09-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HideShowFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.CharField(
                        choices=[
                            ("ITEMS", "Items"),
                            ("SALES", "Sales"),
                            ("PRODUCTS", "Products"),
                        ],
                        max_length=255,
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ModelFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.CharField(
                        choices=[
                            ("ITEMS", "Items"),
                            ("SALES", "Sales"),
                            ("PRODUCTS", "Products"),
                        ],
                        max_length=255,
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PageItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.CharField(
                        choices=[
                            ("ITEMS", "Items"),
                            ("SALES", "Sales"),
                            ("PRODUCTS", "Products"),
                        ],
                        max_length=255,
                    ),
                ),
                ("items_per_page", models.IntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.TextField(blank=True, null=True)),
                ("Description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Product", models.TextField(blank=True, null=True)),
                (
                    "BuyerEmail",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("PurchaseDate", models.DateField(blank=True, null=True)),
                ("Country", models.TextField(blank=True, null=True)),
                ("Price", models.FloatField(blank=True, null=True)),
                (
                    "Refunded",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default="NO",
                        max_length=20,
                    ),
                ),
                (
                    "Currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("EUR", "EUR")],
                        default="USD",
                        max_length=10,
                    ),
                ),
                ("Quantity", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
